services:
  discovery-server:
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - explore-network
    healthcheck:
      test: "curl --fail --silent discovery-server:8761/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

  config-server:
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9091
    healthcheck:
      test: "curl --fail --silent config-server:9091/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 30s
      retries: 5

  gateway-server:
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      ewm-service:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewm_stats_db
    ports:
      - "5433:5432"
    networks:
      - explore-network
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9090
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 15s
      retries: 10
    ports:
      - "9090:9090"
    networks:
      - explore-network

  ewm-event-db:
    image: postgres:16.1
    container_name: postgres-event-db
    restart: always
    environment:
      - POSTGRES_DB=ewm_event_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "6432:5432"
    networks:
      - explore-network
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  ewm-comment-db:
    image: postgres:16.1
    container_name: postgres-comment-db
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_DB=ewm_comment_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - explore-network

  ewm-request-db:
    image: postgres:16.1
    container_name: postgres-request-db
    ports:
      - "6434:5432"
    environment:
      - POSTGRES_DB=ewm_request_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - explore-network

  ewm-user-service:
    build: core/user-service
    container_name: ewm-user-service
    depends_on:
      ewm-event-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-event-db:5432/ewm_event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8082
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-service:
    build: ./core/event-service
    container_name: ewm-service
    restart: always
    depends_on:
      - ewm-event-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-event-db:5432/ewm_event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10
    networks:
      - explore-network

  ewm-comment-service:
    build: core/comment-service
    container_name: ewm-comment-service
    depends_on:
      ewm-comment-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-comment-db:5432/ewm_comment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8083
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-request-service:
    build: core/request-service
    container_name: ewm-request-service
    depends_on:
      ewm-request-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-request-db:5432/ewm_request_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8084
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10


networks:
  explore-network:
    driver: bridge
